### ISSUE TITLE
Bug: CopyUtil geht nicht

### ISSUE THREAD

**Issue by davidbecker** [FI13/afbb-bibo#65]

**Comment by davidbecker** [comment]
@philippwiddra hast du da schon was gemacht?

**Comment by philippwiddra** [comment]
Ich hab mal reingesehen, aber bin nicht sicher ob wir das Problem überhaupt so lösen möchten. Sieht für mich nach keiner sehr sauberen Sache aus.
Spricht (außer den üblichen Gründen) etwas gegen eine saubere Implementierung des `Clonable` Interfaces für alle Modellklassen?
Die Shallow Copy von `Object.clone` deckt in unserem Fall doch schon ca. 90 % der Felder ab.

**Comment by davidbecker** [comment]
Hm, da hast du eigentlich recht. Ich meine in den Fällen wo wir dann mal ein 2. Objekt benutzen (z.B. Typ in Exemplar) wollen wir eigentlich gar nicht das wir eine neue Instanz von Typ bekommen. Ich lass es aber erstmal noch offen falls es so doch aus einem Grund nicht geht

**Comment by philippwiddra** [comment]
Selbst in den Fällen muss sie `clone` Funktion nur überschrieben werden.
Ich guck mir das gleich an und implementiere das.

**Comment by davidbecker** [comment]
:+1:

**Comment by philippwiddra** [comment]
Sollte jetzt funktionieren, kannst ja die Tests noch einmal bei dir ausführen.
Man muss nur, sobald wir andere Objekte in den Klassen referenzieren die `clone` Funktionen ändern, sodass sie die `clone` Methode des referenzierten Objekte aufrufen:
``` java
	@Override
	public Object clone() throws CloneNotSupportedException {
		Copy copyClone = (Copy)super.clone();
		copyClone.setMedium(copyClone.getMedium().clone());
		return copyClone;
	}
```
Ansonsten bleibt es eine shallow copy und es wird auf die selben Objekte verwiesen.

**Comment by davidbecker** [comment]
scheint zu funktionieren, ich würde die Methode nur folgendermaßen anpassen:
```java
	@Override
	public Object clone() {
		try {
			return super.clone();
		} catch (final CloneNotSupportedException e) {
			// swallow exception and return null
			return null;
		}
	}
````
