### ISSUE TITLE
Possible Bug: Clone leitet Aufruf nicht an Kindobjekte weiter

### ISSUE THREAD

**Issue by philippwiddra** [FI13/afbb-bibo#73]
#69 Öffnet jetzt das Problem, dass die Clone Funktion nicht für die Kindobjekte aufgerufen wird.
Das müsste wenn wir es so handhaben wollen, dass Clone wirklich eine Deep Copy zurückgibt, ungefähr so implementiert werden:

``` java
public class Medium extends AbstractPropertyChangeSupport implements Cloneable {

    // ...

    private MediumType type;

    // ...

	@Override
	public Object clone() {
		try {
			Object c = super.clone();
			c.setType(c.getType().clone());
			return c;
		} catch (final CloneNotSupportedException e) {
			// swallow exception and return null
			return null;
		}
	}

    // ...
}
```

Generell sollte es kein Problem darstellen wenn wir das so implementiert lassen wie es ist, solange darauf geachtet wird dass die Felder der Kindobjekten nicht über die Benutzeroberfläche verändert werden können bevor sie anderweitig kopiert werden.

**Comment by davidbecker** [comment]
Stimmt, daran hab ich jetzt nicht gedacht. Ich werde das gleich noch berichtigen
